### ISSUE TITLE
converting to hex has problems

### ISSUE THREAD

**Issue by petrospap** [naomai/php-dominantcolor#1]
Hello, nice app dude!

I try to dechex colorInfo to save to db
something like this

```
$primary = dechex($colorInfo['primary']);
$secondary = dechex($colorInfo['secondary']);
echo ' primary= '. $colorInfo['primary']. ' (dechex='.$primary.') secondary= '.$colorInfo['secondary'].' (dechex='.$secondary.')';

results
primary= 3568751 (dechex=36746f) secondary= 335138 (dechex=51d22)
```

As you can see secondary color has a problem, also this happen and for the palette,
note:  this not occur to all images only when the same color surrounds the picture

image i try to get color info
https://drive.google.com/file/d/1z8VRONRubkHRxlHDWB0RKqpm1aFJ-Ehb/view

**Comment by naomai** [comment]
Hi, thanks for the kind words! That weird value is actually a very dark blue that's all around your image. By default the library is considering dark shades as colors. This is how I expect it to work, but I understand that your case is different. In the last commit, I made some changes to allow tweaking of the algorithm. Can you try adding these to your script?
`
DominantColor::$config->valueLowThreshold = 0.5;
DominantColor::$config->valueLowMultiplier = 0.05;
DominantColor::$config->secondary->saturationMultiplier = 1;
DominantColor::$config->secondary->valueMultiplier = 4;
DominantColor::$config->secondary->countMultiplier = 7;
`

**Comment by petrospap** [comment]
WOW you make lot of changes, try to play and understand what is the best for me ;)

Seems like dechex not make the right job, as i got the same problem with palette

i.e with the same image i got 
```
palette key 0 533031 - dechex= #82227 <-
palette key 1 5273200 - dechex= #507670
palette key 2 200727 - dechex= #31017 <-
palette key 3 5990754 - dechex= #5b6962
palette key 4 198926 - dechex= #3090e <-
```

printf shows the right color but i am horrible with printf, 
is there any way to return color arrays directly to hex?

**Comment by petrospap** [comment]
I rush sometimes, sprintf do the job ;)

**Comment by petrospap** [comment]
I inform you when my site is ready!
