### ISSUE TITLE
Does not work currently: project depends on missing constant from KMeans

### ISSUE THREAD

**Issue by eelke** [naomai/php-dominantcolor#3]
It seems this library depends on an older version of KMeans. 

`Space::SEED_DASV`, as used [on line 22](https://github.com/naomai/php-dominantcolor/blob/527efe5239e0d8a129a4193ab2b6d92cb38c4c35/src/DominantColor.php#L22C60-L22C60) does not exist in the current version of KMeans.

**Comment by naomai** [comment]
Hi @eelke , thanks for letting me know! I updated the library to support newer version of KMeans. 
If there's a need for working PHP7.0 version, I also made a release v0.1.0 with correct dependencies.
